import asyncio,sys,json
import os; sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from playwright.async_api import async_playwright
from mock import install
async def m(w,h):
  async with async_playwright() as p:
    b=await p.chromium.launch();ctx=await b.new_context(viewport={'width':w,'height':h},geolocation={'latitude':13.34,'longitude':74.74},permissions=['geolocation']);pg=await ctx.new_page()
    bad=[];pg.on('response',lambda r: bad.append(r.status.__str__()+' '+r.url[:100]) if r.status>=400 else None)
    errs=[];pg.on('pageerror',lambda e:errs.append(str(e)));pg.on('console',lambda m: errs.append('C:'+m.text) if m.type=='error' else None)
    await install(pg);await pg.goto('http://localhost:8080/report');await pg.wait_for_timeout(1200)
    await pg.click('.hero .btn-primary');await pg.wait_for_timeout(300)
    async def nxt(): await pg.click('#wNext');await pg.wait_for_timeout(300)
    async def step(): return await pg.evaluate('cStep')
    await nxt(); print('step',await step())
    await pg.locator('#cCat button').first.click(); await nxt(); print('step',await step())
    await pg.locator('#cSev button').first.click(); await nxt(); print('step',await step())
    await pg.locator('#cAnimal button').first.click(); await nxt(); print('step',await step())
    opts=await pg.evaluate('[...document.querySelectorAll("#cState option")].map(o=>o.value).filter(Boolean).slice(0,40)')
    st='Karnataka' if 'Karnataka' in opts else opts[0]
    await pg.select_option('#cState',st); await pg.wait_for_timeout(300)
    dopts=await pg.evaluate('[...document.querySelectorAll("#cDistrict option")].map(o=>o.value).filter(Boolean)')
    print(' districts for',st,len(dopts),dopts[:5])
    await pg.select_option('#cDistrict','Udupi' if 'Udupi' in dopts else dopts[0])
    await pg.fill('#cLandmark','Near the Krishna temple car street')
    await nxt(); print('step',await step())
    await pg.evaluate('quickWhen(2)'); await nxt(); print('step',await step())
    await pg.fill('#cCaption','Three community dogs were poisoned near the market this morning.'); await nxt(); print('step',await step())
    fi=pg.locator('#composeModal input[type=file]')
    print(' file inputs',await fi.count())
    if await fi.count(): await fi.first.set_input_files('/tmp/t.jpg'); await pg.wait_for_timeout(400)
    await pg.screenshot(path='/tmp/r_step8.png')
    await nxt()
    print('reporter modal visible',await pg.is_visible('#reporterModal'))
    await pg.fill('#rName','Asha Rao');await pg.fill('#rEmail','asha@example.com');await pg.fill('#rPhone','9876543210')
    await pg.click('#rConsent');await pg.wait_for_timeout(100)
    await pg.screenshot(path='/tmp/r_reporter.png')
    await pg.click('#postBtn');await pg.wait_for_timeout(2500)
    print('success visible',await pg.is_visible('#successModal'),'ref',await pg.inner_text('#successRef') if await pg.locator('#successRef').count() else '')
    calls=await pg.evaluate('__fb.calls.map(c=>c[0]+":"+c[1])');print('firebase calls',calls)
    print('uploads',await pg.evaluate('__fb.uploads'))
    sub=await pg.evaluate('(__fb.calls.find(c=>c[1]==="submitReport")||[])[2]')
    print('payload',json.dumps(sub)[:500] if sub else None)
    await pg.screenshot(path='/tmp/r_success.png')
    await pg.wait_for_timeout(1500)
    print('pdf btn enabled',await pg.is_enabled('#dlPdfBtn'),await pg.inner_text('#dlPdfLbl'))
    async with pg.expect_download() as dl: await pg.click('#dlPdfBtn')
    d=await dl.value;print('downloaded',d.suggested_filename)
    print('bad responses',bad)
    print('errors',errs)
    await b.close()
asyncio.run(m(int(sys.argv[1]),int(sys.argv[2])))
